# rabbitmq_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq-app
  template:
    metadata:
      labels:
        app: rabbitmq-app
    spec:
      containers:
      - name: rabbitmq-app
        image: rabbitmq:management
        ports:
        - containerPort: 5672  # Porta padrão para conexões RabbitMQ
        - containerPort: 15672 # Porta do RabbitMQ Management Plugin